### ISSUE TITLE
Can't hide button

### ISSUE THREAD

**Issue by starofsky** [FokkeZB/nl.fokkezb.button#25]
In your example:
\<Widget id="abc" src="nl.fokkezb.button" onClick="doClick" title="Left (default)" style="bs-default" class="icon" /\>
$.abc.hide();
- button don't hide

**Comment by FokkeZB** [comment]
I just added a test case in the updated demo/test app in the [test](https://github.com/FokkeZB/nl.fokkezb.button/tree/test) branch (see last tab in the app) and I can't reproduce. Please provide a PR with a failing test.
