### ISSUE TITLE
The disabled feature is not working.

### ISSUE THREAD

**Issue by asiby** [FokkeZB/nl.fokkezb.button#30]
Hello Fokke

Very nice module. I have however noticed that when settings the "enabled" to false, it does not work. That button stays enabled and the visual appearance. I tried the following with no success:

- class="disabled"
- enabled="false"
- setting disabledStyle to a JSON object { ... } containing properties about different colours, etc.

Question: Should it be necessary to set disabledStyle if the set style (ex. bs-primary) already has a disabled style defined within. That also does not seem to work.

I have testing all these on Android 6.0.1 in a Nexus 5 and iOS 9.02

I am not sure if I am mishandling something. But if it's a but, I might send you some pull requests.

Cheers

**Comment by starofsky** [comment]
In view file:
<Widget src="nl.fokkezb.button" title="01 " style="ios" id="A01" class="disabled" />
in tss file:
".disabled": {
    enabled: false
}
Or use by program:
In view file:
<Widget src="nl.fokkezb.button" title="01 " style="ios" id="A01" class="disabled" />
In controller file:
$.A01.applyProperties({
        enabled: false
    });

Hope this help you.

**Comment by asiby** [comment]
Thanks a lot. It worked.

I actually looked in the code and figured that I could use applyProperty.

Keep up the great work you are doing.

Cheers

Abdoulaye

**Comment by FokkeZB** [comment]
Thanks for helping @asiby @starofsky !
